"""document flow: iin linkage and expiry reminders

Revision ID: 1f25f6ab9404
Revises: 41217dcc28f5
Create Date: 2026-08-08 15:59:42.216608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1f25f6ab9404'
down_revision: Union[str, None] = '41217dcc28f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_documents', sa.Column('iin', sa.String(length=12), nullable=True))
    # server_default для существующих строк.
    op.add_column('verification_documents', sa.Column('reminders_sent', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_documents', 'reminders_sent')
    op.drop_column('verification_documents', 'iin')
    # ### end Alembic commands ###
