"""cancellation rules

Revision ID: 270012a5f014
Revises: 1f25f6ab9404
Create Date: 2026-08-08 16:14:15.068130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '270012a5f014'
down_revision: Union[str, None] = '1f25f6ab9404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellation_rules',
    sa.Column('hours_before', sa.Integer(), nullable=False),
    sa.Column('penalty_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('hours_before >= 0', name=op.f('ck_cancellation_rules_hours_non_negative')),
    sa.CheckConstraint('penalty_percent >= 0 AND penalty_percent <= 100', name=op.f('ck_cancellation_rules_penalty_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cancellation_rules')),
    sa.UniqueConstraint('hours_before', name='uq_cancellation_rules_hours')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cancellation_rules')
    # ### end Alembic commands ###
