"""initial schema

Revision ID: 294d5cf97c95
Revises: 
Create Date: 2026-08-08 15:05:37.900870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '294d5cf97c95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_ru', sa.String(length=120), nullable=False),
    sa.Column('name_kk', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('code', name=op.f('uq_cities_code'))
    )
    op.create_table('otp_codes',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.Enum('login', 'phone_change', name='otp_purpose', native_enum=False, length=48), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.create_table('promo_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('per_user_limit', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_codes'))
    )
    op.create_index(op.f('ix_promo_codes_code'), 'promo_codes', ['code'], unique=True)
    op.create_table('qualifications',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('vertical', sa.Enum('children', 'elderly', 'disability', 'pets', name='qualification_vertical', native_enum=False, length=48), nullable=True),
    sa.Column('name_ru', sa.String(length=160), nullable=False),
    sa.Column('name_kk', sa.String(length=160), nullable=False),
    sa.Column('requires_document', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qualifications')),
    sa.UniqueConstraint('code', name=op.f('uq_qualifications_code'))
    )
    op.create_table('service_categories',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('vertical', sa.Enum('children', 'elderly', 'disability', 'pets', name='vertical', native_enum=False, length=48), nullable=False),
    sa.Column('name_ru', sa.String(length=160), nullable=False),
    sa.Column('name_kk', sa.String(length=160), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_categories')),
    sa.UniqueConstraint('code', name=op.f('uq_service_categories_code'))
    )
    op.create_index(op.f('ix_service_categories_vertical'), 'service_categories', ['vertical'], unique=False)
    op.create_table('commission_rules',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], name=op.f('fk_commission_rules_category_id_service_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_rules'))
    )
    op.create_table('districts',
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name_ru', sa.String(length=120), nullable=False),
    sa.Column('name_kk', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_districts_city_id_cities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_districts')),
    sa.UniqueConstraint('city_id', 'code', name='uq_districts_city_code')
    )
    op.create_table('services',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name_ru', sa.String(length=160), nullable=False),
    sa.Column('name_kk', sa.String(length=160), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=True),
    sa.Column('description_kk', sa.Text(), nullable=True),
    sa.Column('allowed_price_units', sa.JSON(), nullable=False),
    sa.Column('required_verification_rank', sa.Integer(), nullable=False),
    sa.Column('min_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('supports_urgent', sa.Boolean(), nullable=False),
    sa.Column('is_mvp', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], name=op.f('fk_services_category_id_service_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('code', name=op.f('uq_services_code'))
    )
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('patronymic', sa.String(length=120), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('female', 'male', name='gender', native_enum=False, length=48), nullable=True),
    sa.Column('avatar_key', sa.String(length=512), nullable=True),
    sa.Column('iin_encrypted', sa.String(length=255), nullable=True),
    sa.Column('identity_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locale', sa.Enum('ru', 'kk', name='locale', native_enum=False, length=48), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=True),
    sa.Column('is_customer', sa.Boolean(), nullable=False),
    sa.Column('is_provider', sa.Boolean(), nullable=False),
    sa.Column('staff_role', sa.Enum('moderator', 'admin', name='staff_role', native_enum=False, length=48), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='user_status', native_enum=False, length=48), nullable=False),
    sa.Column('suspended_reason', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_users_city_id_cities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('addresses',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('building', sa.String(length=32), nullable=True),
    sa.Column('apartment', sa.String(length=32), nullable=True),
    sa.Column('entrance', sa.String(length=32), nullable=True),
    sa.Column('intercom', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_addresses_city_id_cities')),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_addresses_district_id_districts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_addresses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_addresses'))
    )
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('devices',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('ios', 'android', 'web', name='device_platform', native_enum=False, length=48), nullable=False),
    sa.Column('push_token', sa.String(length=512), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('locale', sa.Enum('ru', 'kk', name='device_locale', native_enum=False, length=48), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('push_token', name='uq_devices_push_token')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('payouts',
    sa.Column('provider_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'processing', 'paid', 'failed', name='payout_status', native_enum=False, length=48), nullable=False),
    sa.Column('method', sa.Enum('kaspi', 'card', name='payout_method', native_enum=False, length=48), nullable=False),
    sa.Column('destination_mask', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('psp_reference', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_user_id'], ['users.id'], name=op.f('fk_payouts_provider_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payouts'))
    )
    op.create_index(op.f('ix_payouts_batch_id'), 'payouts', ['batch_id'], unique=False)
    op.create_index(op.f('ix_payouts_provider_user_id'), 'payouts', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_table('provider_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('headline', sa.String(length=160), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('video_key', sa.String(length=512), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'active', 'paused', 'suspended', 'rejected', name='provider_status', native_enum=False, length=48), nullable=False),
    sa.Column('verification_level', sa.Enum('level_0', 'level_1', 'level_2', 'level_3', name='verification_level', native_enum=False, length=48), nullable=False),
    sa.Column('verification_level_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('documents_valid_until', sa.Date(), nullable=True),
    sa.Column('city_id', sa.Uuid(), nullable=True),
    sa.Column('base_latitude', sa.Float(), nullable=True),
    sa.Column('base_longitude', sa.Float(), nullable=True),
    sa.Column('work_radius_km', sa.Integer(), nullable=False),
    sa.Column('accepts_urgent', sa.Boolean(), nullable=False),
    sa.Column('accepts_live_in', sa.Boolean(), nullable=False),
    sa.Column('has_car', sa.Boolean(), nullable=False),
    sa.Column('is_non_smoker', sa.Boolean(), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('completed_orders_count', sa.Integer(), nullable=False),
    sa.Column('response_time_minutes', sa.Integer(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_provider_profiles_city_id_cities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_provider_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_provider_profiles'))
    )
    op.create_index(op.f('ix_provider_profiles_status'), 'provider_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_provider_profiles_verification_level'), 'provider_profiles', ['verification_level'], unique=False)
    op.create_table('user_consents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('consent_type', sa.Enum('personal_data', 'public_offer', 'background_check', 'geo_tracking', 'marketing', name='consent_type', native_enum=False, length=48), nullable=False),
    sa.Column('document_version', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_consents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_consents'))
    )
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_table('verification_documents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('id_card', 'selfie', 'criminal_record', 'psych_dispensary', 'narco_dispensary', 'medical_book', 'education', 'certificate', name='document_type', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', name='document_status', native_enum=False, length=48), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('egov_reference', sa.String(length=128), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_verification_documents_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_documents'))
    )
    op.create_index(op.f('ix_verification_documents_document_type'), 'verification_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_verification_documents_status'), 'verification_documents', ['status'], unique=False)
    op.create_index(op.f('ix_verification_documents_user_id'), 'verification_documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_verification_documents_valid_until'), 'verification_documents', ['valid_until'], unique=False)
    op.create_table('verification_requests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_level', sa.Enum('level_0', 'level_1', 'level_2', 'level_3', name='target_verification_level', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'in_review', 'needs_fix', 'approved', 'rejected', name='verification_request_status', native_enum=False, length=48), nullable=False),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('moderator_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_verification_requests_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_verification_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_requests'))
    )
    op.create_index(op.f('ix_verification_requests_status'), 'verification_requests', ['status'], unique=False)
    op.create_index(op.f('ix_verification_requests_user_id'), 'verification_requests', ['user_id'], unique=False)
    op.create_table('document_access_logs',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_document_access_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['verification_documents.id'], name=op.f('fk_document_access_logs_document_id_verification_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_access_logs'))
    )
    op.create_index(op.f('ix_document_access_logs_actor_id'), 'document_access_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_document_access_logs_document_id'), 'document_access_logs', ['document_id'], unique=False)
    op.create_table('favorites',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('provider_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_favorites_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_user_id'], ['provider_profiles.user_id'], name=op.f('fk_favorites_provider_user_id_provider_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'provider_user_id', name=op.f('pk_favorites'))
    )
    op.create_table('order_recurrences',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('provider_user_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('weekday_mask', sa.SmallInteger(), nullable=False),
    sa.Column('time_from', sa.Time(), nullable=False),
    sa.Column('time_to', sa.Time(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_unit', sa.Enum('hour', 'shift', 'day', 'month', name='recurrence_price_unit', native_enum=False, length=48), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_until', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('fk_order_recurrences_address_id_addresses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_order_recurrences_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_user_id'], ['provider_profiles.user_id'], name=op.f('fk_order_recurrences_provider_user_id_provider_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_order_recurrences_service_id_services'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_recurrences'))
    )
    op.create_index(op.f('ix_order_recurrences_customer_id'), 'order_recurrences', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_recurrences_provider_user_id'), 'order_recurrences', ['provider_user_id'], unique=False)
    op.create_table('provider_date_exceptions',
    sa.Column('provider_user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_user_id'], ['provider_profiles.user_id'], name=op.f('fk_provider_date_exceptions_provider_user_id_provider_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_date_exceptions')),
    sa.UniqueConstraint('provider_user_id', 'date', name='uq_provider_date_exceptions_date')
    )
    op.create_index(op.f('ix_provider_date_exceptions_provider_user_id'), 'provider_date_exceptions', ['provider_user_id'], unique=False)
    op.create_table('provider_districts',
    sa.Column('provider_user_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_provider_districts_district_id_districts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_user_id'], ['provider_profiles.user_id'], name=op.f('fk_provider_districts_provider_user_id_provider_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_user_id', 'district_id', name=op.f('pk_provider_districts'))
    )
    op.create_table('provider_languages',
    sa.Column('provider_user_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.Enum('ru', 'kk', 'en', 'tr', name='provider_language', native_enum=False, length=48), nullable=False),
    sa.Column('level', sa.Enum('basic', 'conversational', 'native', name='language_level', native_enum=False, length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_user_id'], ['provider_profiles.user_id'], name=op.f('fk_provider_languages_provider_user_id_provider_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_user_id', 'language', name=op.f('pk_provider_languages'))
    )
    op.create_table('provider_qualifications',
    sa.Column('provider_user_id', sa.Uuid(), nullable=False),
    sa.Column('qualification_id', sa.Uuid(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['verification_documents.id'], name=op.f('fk_provider_qualifications_document_id_verification_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_user_id'], ['provider_profiles.user_id'], name=op.f('fk_provider_qualifications_provider_user_id_provider_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualifications.id'], name=op.f('fk_provider_qualifications_qualification_id_qualifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_user_id', 'qualification_id', name=op.f('pk_provider_qualifications'))
    )
    op.create_table('provider_services',
    sa.Column('provider_user_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_unit', sa.Enum('hour', 'shift', 'day', 'month', name='price_unit', native_enum=False, length=48), nullable=False),
    sa.Column('min_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_provider_services_price_positive')),
    sa.ForeignKeyConstraint(['provider_user_id'], ['provider_profiles.user_id'], name=op.f('fk_provider_services_provider_user_id_provider_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_provider_services_service_id_services'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_services')),
    sa.UniqueConstraint('provider_user_id', 'service_id', 'price_unit', name='uq_provider_services_offer')
    )
    op.create_index(op.f('ix_provider_services_provider_user_id'), 'provider_services', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_provider_services_service_id'), 'provider_services', ['service_id'], unique=False)
    op.create_table('provider_weekly_slots',
    sa.Column('provider_user_id', sa.Uuid(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('time_from', sa.Time(), nullable=False),
    sa.Column('time_to', sa.Time(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_provider_weekly_slots_weekday_range')),
    sa.ForeignKeyConstraint(['provider_user_id'], ['provider_profiles.user_id'], name=op.f('fk_provider_weekly_slots_provider_user_id_provider_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_weekly_slots'))
    )
    op.create_index(op.f('ix_provider_weekly_slots_provider_user_id'), 'provider_weekly_slots', ['provider_user_id'], unique=False)
    op.create_table('verification_interviews',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('interview_type', sa.Enum('video_call', 'recorded', name='interview_type', native_enum=False, length=48), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conducted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recording_key', sa.String(length=512), nullable=True),
    sa.Column('moderator_id', sa.Uuid(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], name=op.f('fk_verification_interviews_moderator_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['verification_requests.id'], name=op.f('fk_verification_interviews_request_id_verification_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_interviews'))
    )
    op.create_index(op.f('ix_verification_interviews_request_id'), 'verification_interviews', ['request_id'], unique=False)
    op.create_table('orders',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('provider_user_id', sa.Uuid(), nullable=True),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('catalog', 'request', name='order_source', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'sent', 'accepted', 'confirmed', 'in_progress', 'completed', 'paid', 'cancelled', 'expired', name='order_status', native_enum=False, length=48), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('address_snapshot', sa.JSON(), nullable=True),
    sa.Column('city_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('price_unit', sa.Enum('hour', 'shift', 'day', 'month', name='order_price_unit', native_enum=False, length=48), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_units', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estimated_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_units', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('final_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('provider_payout_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('required_qualification_ids', sa.JSON(), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_latitude', sa.Float(), nullable=True),
    sa.Column('check_in_longitude', sa.Float(), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_latitude', sa.Float(), nullable=True),
    sa.Column('check_out_longitude', sa.Float(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Enum('customer', 'provider', 'platform', name='cancelled_by', native_enum=False, length=48), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_penalty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recurrence_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name=op.f('fk_orders_address_id_addresses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_orders_city_id_cities')),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_orders_customer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('fk_orders_district_id_districts')),
    sa.ForeignKeyConstraint(['provider_user_id'], ['users.id'], name=op.f('fk_orders_provider_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurrence_id'], ['order_recurrences.id'], name=op.f('fk_orders_recurrence_id_order_recurrences'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_orders_service_id_services'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index(op.f('ix_orders_code'), 'orders', ['code'], unique=True)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index('ix_orders_customer_status', 'orders', ['customer_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_district_id'), 'orders', ['district_id'], unique=False)
    op.create_index(op.f('ix_orders_is_urgent'), 'orders', ['is_urgent'], unique=False)
    op.create_index('ix_orders_open_feed', 'orders', ['status', 'scheduled_start'], unique=False)
    op.create_index('ix_orders_provider_status', 'orders', ['provider_user_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_provider_user_id'), 'orders', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_orders_scheduled_start'), 'orders', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_orders_service_id'), 'orders', ['service_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('chat_threads',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('provider_user_id', sa.Uuid(), nullable=False),
    sa.Column('last_order_id', sa.Uuid(), nullable=True),
    sa.Column('contacts_unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_chat_threads_customer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_order_id'], ['orders.id'], name=op.f('fk_chat_threads_last_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_user_id'], ['users.id'], name=op.f('fk_chat_threads_provider_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_threads')),
    sa.UniqueConstraint('customer_id', 'provider_user_id', name='uq_chat_threads_pair')
    )
    op.create_index(op.f('ix_chat_threads_customer_id'), 'chat_threads', ['customer_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_last_message_at'), 'chat_threads', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_chat_threads_provider_user_id'), 'chat_threads', ['provider_user_id'], unique=False)
    op.create_table('complaints',
    sa.Column('reporter_id', sa.Uuid(), nullable=True),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('safety', 'fraud', 'quality', 'no_show', 'off_platform', 'spam', 'other', name='complaint_category', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_review', 'resolved', 'dismissed', name='complaint_status', native_enum=False, length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('compensation_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_suspended', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_complaints_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_complaints_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_complaints_reporter_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_complaints_target_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints'))
    )
    op.create_index(op.f('ix_complaints_category'), 'complaints', ['category'], unique=False)
    op.create_index(op.f('ix_complaints_reporter_id'), 'complaints', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index(op.f('ix_complaints_target_user_id'), 'complaints', ['target_user_id'], unique=False)
    op.create_table('order_responses',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('provider_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'withdrawn', name='order_response_status', native_enum=False, length=48), nullable=False),
    sa.Column('offered_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_responses_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_user_id'], ['provider_profiles.user_id'], name=op.f('fk_order_responses_provider_user_id_provider_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_responses')),
    sa.UniqueConstraint('order_id', 'provider_user_id', name='uq_order_responses_provider')
    )
    op.create_index(op.f('ix_order_responses_order_id'), 'order_responses', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_responses_provider_user_id'), 'order_responses', ['provider_user_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('draft', 'published', 'sent', 'accepted', 'confirmed', 'in_progress', 'completed', 'paid', 'cancelled', 'expired', name='history_from_status', native_enum=False, length=48), nullable=True),
    sa.Column('to_status', sa.Enum('draft', 'published', 'sent', 'accepted', 'confirmed', 'in_progress', 'completed', 'paid', 'cancelled', 'expired', name='history_to_status', native_enum=False, length=48), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_order_status_history_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_status_history_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_history'))
    )
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('payer_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('kaspi', 'card', 'apple_pay', 'google_pay', name='payment_provider', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('pending', 'held', 'captured', 'refunded', 'partially_refunded', 'failed', 'cancelled', name='payment_status', native_enum=False, length=48), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('captured_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('refunded_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('psp_reference', sa.String(length=128), nullable=True),
    sa.Column('card_mask', sa.String(length=24), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('receipt_number', sa.String(length=64), nullable=True),
    sa.Column('receipt_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], name=op.f('fk_payments_payer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_payments_idempotency_key'))
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_psp_reference'), 'payments', ['psp_reference'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('payout_items',
    sa.Column('payout_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_payout_items_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], name=op.f('fk_payout_items_payout_id_payouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payout_items')),
    sa.UniqueConstraint('order_id', name='uq_payout_items_order')
    )
    op.create_index(op.f('ix_payout_items_payout_id'), 'payout_items', ['payout_id'], unique=False)
    op.create_table('reviews',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('customer_to_provider', 'provider_to_customer', name='review_direction', native_enum=False, length=48), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('rating_punctuality', sa.SmallInteger(), nullable=True),
    sa.Column('rating_attitude', sa.SmallInteger(), nullable=True),
    sa.Column('rating_communication', sa.SmallInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'published', 'rejected', name='review_status', native_enum=False, length=48), nullable=False),
    sa.Column('moderation_notes', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('editable_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_reviews_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reviews_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['users.id'], name=op.f('fk_reviews_target_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('order_id', 'direction', name='uq_reviews_order_direction')
    )
    op.create_index(op.f('ix_reviews_order_id'), 'reviews', ['order_id'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index('ix_reviews_target_status', 'reviews', ['target_id', 'status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=True),
    sa.Column('message_type', sa.Enum('text', 'image', 'audio', 'system', name='message_type', native_enum=False, length=48), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('raw_body', sa.Text(), nullable=True),
    sa.Column('contacts_masked', sa.Boolean(), nullable=False),
    sa.Column('attachment_key', sa.String(length=512), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_chat_messages_sender_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], name=op.f('fk_chat_messages_thread_id_chat_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_thread_created', 'chat_messages', ['thread_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_thread_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_reviews_target_status', table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_order_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_payout_items_payout_id'), table_name='payout_items')
    op.drop_table('payout_items')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_psp_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_responses_provider_user_id'), table_name='order_responses')
    op.drop_index(op.f('ix_order_responses_order_id'), table_name='order_responses')
    op.drop_table('order_responses')
    op.drop_index(op.f('ix_complaints_target_user_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_reporter_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_chat_threads_provider_user_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_last_message_at'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_customer_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_service_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_scheduled_start'), table_name='orders')
    op.drop_index(op.f('ix_orders_provider_user_id'), table_name='orders')
    op.drop_index('ix_orders_provider_status', table_name='orders')
    op.drop_index('ix_orders_open_feed', table_name='orders')
    op.drop_index(op.f('ix_orders_is_urgent'), table_name='orders')
    op.drop_index(op.f('ix_orders_district_id'), table_name='orders')
    op.drop_index('ix_orders_customer_status', table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_code'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_verification_interviews_request_id'), table_name='verification_interviews')
    op.drop_table('verification_interviews')
    op.drop_index(op.f('ix_provider_weekly_slots_provider_user_id'), table_name='provider_weekly_slots')
    op.drop_table('provider_weekly_slots')
    op.drop_index(op.f('ix_provider_services_service_id'), table_name='provider_services')
    op.drop_index(op.f('ix_provider_services_provider_user_id'), table_name='provider_services')
    op.drop_table('provider_services')
    op.drop_table('provider_qualifications')
    op.drop_table('provider_languages')
    op.drop_table('provider_districts')
    op.drop_index(op.f('ix_provider_date_exceptions_provider_user_id'), table_name='provider_date_exceptions')
    op.drop_table('provider_date_exceptions')
    op.drop_index(op.f('ix_order_recurrences_provider_user_id'), table_name='order_recurrences')
    op.drop_index(op.f('ix_order_recurrences_customer_id'), table_name='order_recurrences')
    op.drop_table('order_recurrences')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_document_access_logs_document_id'), table_name='document_access_logs')
    op.drop_index(op.f('ix_document_access_logs_actor_id'), table_name='document_access_logs')
    op.drop_table('document_access_logs')
    op.drop_index(op.f('ix_verification_requests_user_id'), table_name='verification_requests')
    op.drop_index(op.f('ix_verification_requests_status'), table_name='verification_requests')
    op.drop_table('verification_requests')
    op.drop_index(op.f('ix_verification_documents_valid_until'), table_name='verification_documents')
    op.drop_index(op.f('ix_verification_documents_user_id'), table_name='verification_documents')
    op.drop_index(op.f('ix_verification_documents_status'), table_name='verification_documents')
    op.drop_index(op.f('ix_verification_documents_document_type'), table_name='verification_documents')
    op.drop_table('verification_documents')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_provider_profiles_verification_level'), table_name='provider_profiles')
    op.drop_index(op.f('ix_provider_profiles_status'), table_name='provider_profiles')
    op.drop_table('provider_profiles')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_provider_user_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_batch_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_services_category_id'), table_name='services')
    op.drop_table('services')
    op.drop_table('districts')
    op.drop_table('commission_rules')
    op.drop_index(op.f('ix_service_categories_vertical'), table_name='service_categories')
    op.drop_table('service_categories')
    op.drop_table('qualifications')
    op.drop_index(op.f('ix_promo_codes_code'), table_name='promo_codes')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_table('cities')
    # ### end Alembic commands ###
