"""hybrid monetization: placements and service monetization type

Revision ID: 41217dcc28f5
Revises: 294d5cf97c95
Create Date: 2026-08-08 15:54:53.394428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41217dcc28f5'
down_revision: Union[str, None] = '294d5cf97c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placements',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('provider_user_id', sa.Uuid(), nullable=False),
    sa.Column('monthly_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_status', sa.Enum('pending', 'paid', 'waived', name='placement_fee_status', native_enum=False, length=48), nullable=False),
    sa.Column('fee_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('guarantee_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replacement_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replacement_reason', sa.Text(), nullable=True),
    sa.Column('replacement_of_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], name=op.f('fk_placements_customer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_placements_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_user_id'], ['users.id'], name=op.f('fk_placements_provider_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replacement_of_id'], ['placements.id'], name=op.f('fk_placements_replacement_of_id_placements'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placements')),
    sa.UniqueConstraint('order_id', name=op.f('uq_placements_order_id'))
    )
    op.create_index(op.f('ix_placements_customer_id'), 'placements', ['customer_id'], unique=False)
    op.create_index(op.f('ix_placements_fee_status'), 'placements', ['fee_status'], unique=False)
    op.create_index(op.f('ix_placements_provider_user_id'), 'placements', ['provider_user_id'], unique=False)
    # server_default нужен для уже существующих строк services.
    op.add_column('services', sa.Column('monetization_type', sa.Enum('commission', 'placement_fee', name='monetization_type', native_enum=False, length=48), nullable=False, server_default='commission'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'monetization_type')
    op.drop_index(op.f('ix_placements_provider_user_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_fee_status'), table_name='placements')
    op.drop_index(op.f('ix_placements_customer_id'), table_name='placements')
    op.drop_table('placements')
    # ### end Alembic commands ###
