"""webhook events

Revision ID: 4d73820fb93c
Revises: 270012a5f014
Create Date: 2026-08-09 10:40:53.713081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4d73820fb93c'
down_revision: Union[str, None] = '270012a5f014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('source', 'event_id', name='uq_webhook_events_source_event')
    )
    op.create_index(op.f('ix_webhook_events_source'), 'webhook_events', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_source'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
