"""sms journal and kyc sessions

Revision ID: 9a27d385bc14
Revises: 4d73820fb93c
Create Date: 2026-08-09 11:07:36.961258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a27d385bc14'
down_revision: Union[str, None] = '4d73820fb93c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_session_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('created', 'pending', 'passed', 'failed', 'expired', name='kyc_session_status', native_enum=False, length=48), nullable=False),
    sa.Column('iin', sa.String(length=12), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('birth_date', sa.String(length=32), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_kyc_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kyc_sessions'))
    )
    op.create_index(op.f('ix_kyc_sessions_provider_session_id'), 'kyc_sessions', ['provider_session_id'], unique=True)
    op.create_index(op.f('ix_kyc_sessions_status'), 'kyc_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_kyc_sessions_user_id'), 'kyc_sessions', ['user_id'], unique=False)
    op.create_table('sms_messages',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'failed', 'expired', name='sms_status', native_enum=False, length=48), nullable=False),
    sa.Column('provider_message_id', sa.String(length=64), nullable=True),
    sa.Column('segments', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sms_messages_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sms_messages'))
    )
    op.create_index(op.f('ix_sms_messages_phone'), 'sms_messages', ['phone'], unique=False)
    op.create_index('ix_sms_messages_phone_created', 'sms_messages', ['phone', 'created_at'], unique=False)
    op.create_index(op.f('ix_sms_messages_provider_message_id'), 'sms_messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_sms_messages_status'), 'sms_messages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_messages_status'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_provider_message_id'), table_name='sms_messages')
    op.drop_index('ix_sms_messages_phone_created', table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_phone'), table_name='sms_messages')
    op.drop_table('sms_messages')
    op.drop_index(op.f('ix_kyc_sessions_user_id'), table_name='kyc_sessions')
    op.drop_index(op.f('ix_kyc_sessions_status'), table_name='kyc_sessions')
    op.drop_index(op.f('ix_kyc_sessions_provider_session_id'), table_name='kyc_sessions')
    op.drop_table('kyc_sessions')
    # ### end Alembic commands ###
